/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CellsViewer.java
 *
 * Created on 18-Aug-2009, 14:34:08
 */
package heartsim.gui;

import java.awt.Dimension;

/**
 *
 * @author Lee Boynton
 */
public class CellsViewer extends javax.swing.JFrame
{
    /** Creates new form CellsViewer */
    public CellsViewer()
    {
        initComponents();
    }

    public CellsViewer(boolean[][] cells)
    {
        initComponents();
        binaryPlotPanel1.setPreferredSize(new Dimension(cells[0].length, cells.length));
        binaryPlotPanel1.setSize(cells[0].length, cells.length);
        binaryPlotPanel1.setSize(binaryPlotPanel1.getSize());
        pack();
        binaryPlotPanel1.setCells(cells);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        binaryPlotPanel1 = new heartsim.gui.BinaryPlotPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout binaryPlotPanel1Layout = new javax.swing.GroupLayout(binaryPlotPanel1);
        binaryPlotPanel1.setLayout(binaryPlotPanel1Layout);
        binaryPlotPanel1Layout.setHorizontalGroup(
            binaryPlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        binaryPlotPanel1Layout.setVerticalGroup(
            binaryPlotPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(binaryPlotPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(binaryPlotPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new CellsViewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private heartsim.gui.BinaryPlotPanel binaryPlotPanel1;
    // End of variables declaration//GEN-END:variables
}
