/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUI.java
 *
 * Created on 15-Jun-2009, 13:37:52
 */
package catest.gui;

import catest.Nishiyama;
import javax.swing.SwingWorker;
import javax.swing.UIManager;

/**
 *
 * @author Lee Boynton
 */
public class MainUI extends javax.swing.JFrame
{
    private Nishiyama nishiyama;
    private SwingWorker worker;
    private int time;

    /** Creates new form MainUI */
    public MainUI()
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex)
        {
            System.err.println("Unable to use system look and feel");
        }
        initComponents();
        this.setLocationRelativeTo(null);
        nishiyama = new Nishiyama();
        nishiyama.initCells();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDisplay = new BinaryPlotPanel(400, 400);
        toolbar = new javax.swing.JToolBar();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblN = new javax.swing.JLabel();
        txtN = new javax.swing.JTextField();
        lblDelta1 = new javax.swing.JLabel();
        txtDelta1 = new javax.swing.JTextField();
        lblDelta2 = new javax.swing.JLabel();
        txtDelta2 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nishiyama");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout pnlDisplayLayout = new javax.swing.GroupLayout(pnlDisplay);
        pnlDisplay.setLayout(pnlDisplayLayout);
        pnlDisplayLayout.setHorizontalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        pnlDisplayLayout.setVerticalGroup(
            pnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        toolbar.setRollover(true);

        lblTime.setText("Time:");
        lblTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 4));
        toolbar.add(lblTime);

        txtTime.setText("400");
        txtTime.setPreferredSize(new java.awt.Dimension(50, 25));
        toolbar.add(txtTime);

        lblN.setText("N:");
        lblN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 4));
        toolbar.add(lblN);

        txtN.setText("5");
        txtN.setPreferredSize(new java.awt.Dimension(50, 25));
        toolbar.add(txtN);

        lblDelta1.setText("Delta1:");
        lblDelta1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 4));
        toolbar.add(lblDelta1);

        txtDelta1.setText("3");
        txtDelta1.setPreferredSize(new java.awt.Dimension(50, 25));
        toolbar.add(txtDelta1);

        lblDelta2.setText("Delta2:");
        lblDelta2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 4));
        toolbar.add(lblDelta2);

        txtDelta2.setText("7");
        txtDelta2.setPreferredSize(new java.awt.Dimension(50, 25));
        toolbar.add(txtDelta2);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        toolbar.add(btnStart);

        btnStop.setText("Stop");
        btnStop.setFocusable(false);
        btnStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });
        toolbar.add(btnStop);

        btnReset.setText("Reset");
        btnReset.setFocusable(false);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        toolbar.add(btnReset);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
            .addComponent(pnlDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartActionPerformed
    {//GEN-HEADEREND:event_btnStartActionPerformed
        nishiyama.setDelta1(Integer.parseInt(txtDelta1.getText()));
        nishiyama.setDelta2(Integer.parseInt(txtDelta2.getText()));
        nishiyama.setN(Integer.parseInt(txtN.getText()));
        nishiyama.initCells();
        pnlDisplay.repaint();

        worker = new SwingWorker<Object, Void>()
        {
            @Override
            public Object doInBackground() throws Exception
            {
                byte[] data = ((BinaryPlotPanel) pnlDisplay).getBuffer();

                int[][] u = nishiyama.getU();
                time = Integer.parseInt(txtTime.getText());

                for (int t = 0; t < time; t++)
                {
                    int k = 0;

                    for (int i = 0; i < u.length; i++)
                    {
                        for (int j = 0; j < u[0].length; j++)
                        {
                            byte val = (byte) u[i][j];
                            if (val == 0)
                            {
                                data[k] = -10;
                            }
                            else
                            {
                                data[k] = (byte) u[i][j];
                            }
                            k++;
                        }
                    }

                    nishiyama.step();
                    pnlDisplay.repaint();
                }

                return new Object();
            }
        };

        worker.execute();

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        nishiyama.initCells();
        ((BinaryPlotPanel) pnlDisplay).reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopActionPerformed
    {//GEN-HEADEREND:event_btnStopActionPerformed
        time = 0;
    }//GEN-LAST:event_btnStopActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        pnlDisplay.setSize(pnlDisplay.getSize());
        nishiyama.setSize(pnlDisplay.getSize());
    }//GEN-LAST:event_formComponentResized

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel lblDelta1;
    private javax.swing.JLabel lblDelta2;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlDisplay;
    private javax.swing.JToolBar toolbar;
    private javax.swing.JTextField txtDelta1;
    private javax.swing.JTextField txtDelta2;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
