/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ArrayPanel2.java
 *
 * Created on 06-Sep-2009, 17:38:39
 */
package heartsim.gui.component;

import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Lee Boynton
 */
public class ArrayPanel extends javax.swing.JPanel
{
    private int[][] array;

    public void setArray(int[][] array)
    {
        this.array = array;

        initComponents();

        for (int row = 0; row < array.length; row++)
        {
            for (int col = 0; col < array[row].length; col++)
            {
                this.add(new JLabel(String.valueOf(array[row][col])));
            }
        }

        this.setPreferredSize(new Dimension(getWidth() * 15, getHeight() * 5));
    }

    public int getArrayHeight()
    {
        return array.length;
    }

    public int getArrayWidth()
    {
        return array[0].length;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
